/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/iamfo470/phd/everparse/opt/karamel/krml -fstar /home/iamfo470/phd/everparse/opt/FStar/out/bin/fstar.exe -skip-compilation -skip-linking -tmpdir extracted -no-prefix ICS.Glue.Spec ICS.Glue.Spec.fst
  F* version: <unknown>
  KaRaMeL version: fb36fecb
 */

#ifndef internal_Prims_H
#define internal_Prims_H

#include "krmllib.h"

extern bool Prims_op_LessThanOrEqual(krml_checked_int_t x0, krml_checked_int_t x1);


#define internal_Prims_H_DEFINED
#endif /* internal_Prims_H */
