/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/iamfo470/phd/everparse/opt/karamel/krml -fstar /home/iamfo470/phd/everparse/opt/FStar/out/bin/fstar.exe -skip-compilation -skip-linking -tmpdir extracted -no-prefix ICS.Glue.Spec ICS.Glue.Spec.fst
  F* version: <unknown>
  KaRaMeL version: fb36fecb
 */

#include "ICS_Glue_Spec.h"

#include "internal/Prims.h"

krml_checked_int_t max_payload_size = (krml_checked_int_t)1500;

bool uu___is_ResultOK(validation_result projectee)
{
  switch (projectee)
  {
    case ResultOK:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool uu___is_ResultSyntaxError(validation_result projectee)
{
  switch (projectee)
  {
    case ResultSyntaxError:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool uu___is_ResultPolicyReject(validation_result projectee)
{
  switch (projectee)
  {
    case ResultPolicyReject:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool uu___is_ResultInvalidFC(validation_result projectee)
{
  switch (projectee)
  {
    case ResultInvalidFC:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool uu___is_ResultTooShort(validation_result projectee)
{
  switch (projectee)
  {
    case ResultTooShort:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool well_formed(krml_checked_int_t msg)
{
  return Prims_op_LessThanOrEqual(msg, max_payload_size);
}

K___bool_ICS_Glue_Spec_validation_result process_and_forward(krml_checked_int_t msg)
{
  if (!well_formed(msg))
    return ((K___bool_ICS_Glue_Spec_validation_result){ .fst = false, .snd = ResultTooShort });
  else
  {
    validation_result result = validate(msg);
    if (result == ResultOK)
      return ((K___bool_ICS_Glue_Spec_validation_result){ .fst = true, .snd = ResultOK });
    else
      return ((K___bool_ICS_Glue_Spec_validation_result){ .fst = false, .snd = result });
  }
}

K___bool_ICS_Glue_Spec_validation_result process_and_forward_response(krml_checked_int_t msg)
{
  if (!well_formed(msg))
    return ((K___bool_ICS_Glue_Spec_validation_result){ .fst = false, .snd = ResultTooShort });
  else
  {
    validation_result result = validate_response(msg);
    if (result == ResultOK)
      return ((K___bool_ICS_Glue_Spec_validation_result){ .fst = true, .snd = ResultOK });
    else
      return ((K___bool_ICS_Glue_Spec_validation_result){ .fst = false, .snd = result });
  }
}

