/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/iamfo470/phd/everparse/opt/karamel/krml -fstar /home/iamfo470/phd/everparse/opt/FStar/out/bin/fstar.exe -skip-compilation -skip-linking -tmpdir extracted -no-prefix ICS.Glue.Spec ICS.Glue.Spec.fst
  F* version: <unknown>
  KaRaMeL version: fb36fecb
 */

#ifndef ICS_Glue_Spec_H
#define ICS_Glue_Spec_H

#include "krmllib.h"

extern krml_checked_int_t max_payload_size;

#define ResultOK 0
#define ResultSyntaxError 1
#define ResultPolicyReject 2
#define ResultInvalidFC 3
#define ResultTooShort 4

typedef uint8_t validation_result;

bool uu___is_ResultOK(validation_result projectee);

bool uu___is_ResultSyntaxError(validation_result projectee);

bool uu___is_ResultPolicyReject(validation_result projectee);

bool uu___is_ResultInvalidFC(validation_result projectee);

bool uu___is_ResultTooShort(validation_result projectee);

typedef krml_checked_int_t message;

bool well_formed(krml_checked_int_t msg);

extern validation_result validate(krml_checked_int_t msg);

typedef struct K___bool_ICS_Glue_Spec_validation_result_s
{
  bool fst;
  validation_result snd;
}
K___bool_ICS_Glue_Spec_validation_result;

K___bool_ICS_Glue_Spec_validation_result process_and_forward(krml_checked_int_t msg);

extern validation_result validate_response(krml_checked_int_t msg);

K___bool_ICS_Glue_Spec_validation_result process_and_forward_response(krml_checked_int_t msg);


#define ICS_Glue_Spec_H_DEFINED
#endif /* ICS_Glue_Spec_H */
