/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/iamfo470/phd/everparse/opt/karamel/krml -fstar /home/iamfo470/phd/everparse/opt/FStar/out/bin/fstar.exe -skip-compilation -skip-linking -tmpdir /home/iamfo470/phd/camkes-vm-examples/projects/ics_gateway_x86/verified_glue/extracted_complete -no-prefix ICS.Glue.Complete -bundle ICS.Glue.Complete=* ICS.Glue.Complete.fst
  F* version: <unknown>
  KaRaMeL version: fb36fecb
 */

#ifndef ICS_Glue_Complete_H
#define ICS_Glue_Complete_H

#include "krmllib.h"

extern uint8_t modbus_validate_request(uint8_t *payload, uint32_t len);

extern uint8_t modbus_validate_response(uint8_t *payload, uint32_t len);

uint16_t read_u16_le(uint8_t *buf, uint32_t offset);

typedef struct K___bool_uint8_t_s
{
  bool fst;
  uint8_t snd;
}
K___bool_uint8_t;

K___bool_uint8_t validate_and_decide(uint8_t *payload, uint32_t len, bool is_request);

K___bool_uint8_t process_inbound(uint8_t *in_dp, uint8_t *out_dp);

K___bool_uint8_t process_outbound(uint8_t *in_dp, uint8_t *out_dp);


#define ICS_Glue_Complete_H_DEFINED
#endif /* ICS_Glue_Complete_H */
