/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/iamfo470/phd/everparse/opt/karamel/krml -fstar /home/iamfo470/phd/everparse/opt/FStar/out/bin/fstar.exe -skip-compilation -skip-linking -tmpdir /home/iamfo470/phd/camkes-vm-examples/projects/ics_gateway_x86/verified_glue/extracted_complete -no-prefix ICS.Glue.Complete -bundle ICS.Glue.Complete=* ICS.Glue.Complete.fst
  F* version: <unknown>
  KaRaMeL version: fb36fecb
 */

#include "ICS_Glue_Complete.h"

uint16_t read_u16_le(uint8_t *buf, uint32_t offset)
{
  uint8_t lo = buf[offset];
  uint8_t hi = buf[offset + 1U];
  return (uint32_t)(uint16_t)lo + ((uint32_t)(uint16_t)hi << 8U);
}

K___bool_uint8_t validate_and_decide(uint8_t *payload, uint32_t len, bool is_request)
{
  if (len == 0U)
    return ((K___bool_uint8_t){ .fst = false, .snd = 4U });
  else if (len < 1U)
    return ((K___bool_uint8_t){ .fst = false, .snd = 4U });
  else if (len > 60000U)
    return ((K___bool_uint8_t){ .fst = false, .snd = 5U });
  else
  {
    uint8_t result;
    if (is_request)
      result = modbus_validate_request(payload, len);
    else
      result = modbus_validate_response(payload, len);
    if (result == 0U)
      return ((K___bool_uint8_t){ .fst = true, .snd = 0U });
    else
      return ((K___bool_uint8_t){ .fst = false, .snd = result });
  }
}

K___bool_uint8_t process_inbound(uint8_t *in_dp, uint8_t *out_dp)
{
  uint16_t payload_len_u16 = read_u16_le(in_dp, 39U);
  uint32_t payload_len = (uint32_t)payload_len_u16;
  if (41U + payload_len > 65536U)
    return ((K___bool_uint8_t){ .fst = false, .snd = 6U });
  else
  {
    uint8_t *payload_ptr = in_dp + 41U;
    K___bool_uint8_t scrut = validate_and_decide(payload_ptr, payload_len, true);
    bool forwarded = scrut.fst;
    uint8_t result = scrut.snd;
    if (forwarded)
    {
      uint32_t copy_len = 41U + payload_len;
      memcpy(out_dp, in_dp, copy_len * sizeof (uint8_t));
      return ((K___bool_uint8_t){ .fst = true, .snd = result });
    }
    else
      return ((K___bool_uint8_t){ .fst = false, .snd = result });
  }
}

K___bool_uint8_t process_outbound(uint8_t *in_dp, uint8_t *out_dp)
{
  uint16_t payload_len_u16 = read_u16_le(in_dp, 39U);
  uint32_t payload_len = (uint32_t)payload_len_u16;
  if (41U + payload_len > 65536U)
    return ((K___bool_uint8_t){ .fst = false, .snd = 6U });
  else
  {
    uint8_t *payload_ptr = in_dp + 41U;
    K___bool_uint8_t scrut = validate_and_decide(payload_ptr, payload_len, false);
    bool forwarded = scrut.fst;
    uint8_t result = scrut.snd;
    if (forwarded)
    {
      uint32_t copy_len = 41U + payload_len;
      memcpy(out_dp, in_dp, copy_len * sizeof (uint8_t));
      return ((K___bool_uint8_t){ .fst = true, .snd = result });
    }
    else
      return ((K___bool_uint8_t){ .fst = false, .snd = result });
  }
}

