/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/iamfo470/phd/everparse/opt/karamel/krml -fstar /home/iamfo470/phd/everparse/opt/FStar/out/bin/fstar.exe -skip-compilation -skip-linking -tmpdir extracted_lowstar -no-prefix ICS.Glue.LowStar -bundle ICS.Glue.LowStar=* ICS.Glue.LowStar.fst
  F* version: <unknown>
  KaRaMeL version: fb36fecb
 */

#ifndef ICS_Glue_LowStar_H
#define ICS_Glue_LowStar_H

#include "krmllib.h"

extern uint8_t modbus_validate_request(uint8_t *payload, uint32_t len);

extern uint8_t modbus_validate_response(uint8_t *payload, uint32_t len);

typedef struct K___bool_uint8_t_s
{
  bool fst;
  uint8_t snd;
}
K___bool_uint8_t;

K___bool_uint8_t validate_and_decide_request(uint8_t *payload, uint32_t len);

K___bool_uint8_t validate_and_decide_response(uint8_t *payload, uint32_t len);

K___bool_uint8_t process_request(uint8_t *in_buf, uint8_t *out_buf, uint32_t len);

K___bool_uint8_t process_response(uint8_t *in_buf, uint8_t *out_buf, uint32_t len);


#define ICS_Glue_LowStar_H_DEFINED
#endif /* ICS_Glue_LowStar_H */
