/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/iamfo470/phd/everparse/opt/karamel/krml -fstar /home/iamfo470/phd/everparse/opt/FStar/out/bin/fstar.exe -skip-compilation -skip-linking -tmpdir extracted_lowstar -no-prefix ICS.Glue.LowStar -bundle ICS.Glue.LowStar=* ICS.Glue.LowStar.fst
  F* version: <unknown>
  KaRaMeL version: fb36fecb
 */

#include "ICS_Glue_LowStar.h"

K___bool_uint8_t validate_and_decide_request(uint8_t *payload, uint32_t len)
{
  if (len > 1500U)
    return ((K___bool_uint8_t){ .fst = false, .snd = 4U });
  else
  {
    uint8_t result = modbus_validate_request(payload, len);
    if (result == 0U)
      return ((K___bool_uint8_t){ .fst = true, .snd = 0U });
    else
      return ((K___bool_uint8_t){ .fst = false, .snd = result });
  }
}

K___bool_uint8_t validate_and_decide_response(uint8_t *payload, uint32_t len)
{
  if (len > 1500U)
    return ((K___bool_uint8_t){ .fst = false, .snd = 4U });
  else
  {
    uint8_t result = modbus_validate_response(payload, len);
    if (result == 0U)
      return ((K___bool_uint8_t){ .fst = true, .snd = 0U });
    else
      return ((K___bool_uint8_t){ .fst = false, .snd = result });
  }
}

K___bool_uint8_t process_request(uint8_t *in_buf, uint8_t *out_buf, uint32_t len)
{
  K___bool_uint8_t scrut = validate_and_decide_request(in_buf, len);
  bool forwarded = scrut.fst;
  uint8_t result = scrut.snd;
  if (forwarded)
  {
    memcpy(out_buf, in_buf, len * sizeof (uint8_t));
    return ((K___bool_uint8_t){ .fst = true, .snd = result });
  }
  else
    return ((K___bool_uint8_t){ .fst = false, .snd = result });
}

K___bool_uint8_t process_response(uint8_t *in_buf, uint8_t *out_buf, uint32_t len)
{
  K___bool_uint8_t scrut = validate_and_decide_response(in_buf, len);
  bool forwarded = scrut.fst;
  uint8_t result = scrut.snd;
  if (forwarded)
  {
    memcpy(out_buf, in_buf, len * sizeof (uint8_t));
    return ((K___bool_uint8_t){ .fst = true, .snd = result });
  }
  else
    return ((K___bool_uint8_t){ .fst = false, .snd = result });
}

